# imagem base do Node.js na versão nescessaria
FROM node:16.0.0

# Diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar o  package-lock.json para o contêiner
COPY package-lock.json ./

# Instalar as dependências do projeto
RUN npm install

# Copiar o restante do código do projeto para o contêiner
COPY . .

# Expor a porta que a aplicação irá usar (no caso, porta 5500)
EXPOSE 5500

# iniciar a aplicação
CMD ["npm", "start"]